#!/bin/bash
# Install dotfiles via stow
# Run from the dotfiles directory

set -e
cd "$(dirname "$0")"

# Install stow if missing
if ! command -v stow &> /dev/null; then
    echo "Installing stow..."
    if command -v apt &> /dev/null; then
        sudo apt install -y stow
    elif command -v brew &> /dev/null; then
        brew install stow
    else
        echo "Please install stow manually"
        exit 1
    fi
fi

# Clean up ~/.bashrc.d so stow can create its symlink cleanly
if [ -L ~/.bashrc.d ] && [ ! -e ~/.bashrc.d ]; then
    echo "Removing broken .bashrc.d symlink..."
    rm ~/.bashrc.d
elif [ -d ~/.bashrc.d ] && [ ! -L ~/.bashrc.d ]; then
    echo "Removing existing .bashrc.d directory..."
    rm -rf ~/.bashrc.d
fi

# Install git-delta on Linux
if [[ "$(uname)" == "Linux" ]] && ! command -v delta &> /dev/null; then
    echo "Installing git-delta..."
    DELTA_VERSION="0.18.2"
    curl -sLO "https://github.com/dandavison/delta/releases/download/${DELTA_VERSION}/git-delta_${DELTA_VERSION}_amd64.deb"
    sudo dpkg -i "git-delta_${DELTA_VERSION}_amd64.deb"
    rm "git-delta_${DELTA_VERSION}_amd64.deb"
fi

# Remove generated settings.json so stow can recreate the symlink
# (install.sh replaces it with a merged real file; stow needs a clean target)
if [ -f ~/.claude/settings.json ] && [ ! -L ~/.claude/settings.json ]; then
    echo "Removing generated settings.json for re-stow..."
    rm -f ~/.claude/settings.json
fi

# Same treatment for Codex hooks: private hook fragments are merged into the
# public hooks file after stowing.
if [ -f ~/.codex/hooks.json ] && [ ! -L ~/.codex/hooks.json ]; then
    echo "Removing generated Codex hooks.json for re-stow..."
    rm -f ~/.codex/hooks.json
fi

# Same treatment for AGENTS.md: install.sh replaces the stow symlink with a
# real merged file (public + private concatenated). Clean it up so stow can
# recreate the symlink before merging.
if [ -f ~/.config/AGENTS.md ] && [ ! -L ~/.config/AGENTS.md ]; then
    echo "Removing generated AGENTS.md for re-stow..."
    rm -f ~/.config/AGENTS.md
fi

# Clean up legacy per-file symlinks from previous stow layouts
# (skills/agents used to stow into ~/.claude/{skills,agents}; they now live in
# ~/.local/share/{skills,subagents} and ~/.claude/{skills,agents} are dir symlinks)
for legacy in ~/.claude/skills ~/.claude/agents; do
    if [ -d "$legacy" ] && [ ! -L "$legacy" ]; then
        # Only remove if it contains nothing but symlinks (stow-managed)
        if [ -z "$(find "$legacy" -type f -print -quit 2>/dev/null)" ]; then
            echo "Removing legacy stow dir $legacy..."
            rm -rf "$legacy"
        else
            echo "WARNING: $legacy contains real files; skipping migration. Review manually."
        fi
    fi
done

# Point this repo's hooks at the versioned hooks/ directory
git -C "$(pwd)" config core.hooksPath hooks

# Detect files that should be stow-managed symlinks but were written directly
# into $HOME instead. This is the common cause of confusing stow conflicts for
# shared agent assets.
detect_unmanaged_stow_files() {
    local repo_root=$1 package=$2
    local package_root="$repo_root/$package"
    [ -d "$package_root" ] || return 0

    target_has_symlink_ancestor() {
        local path=$1
        while [ "$path" != "$HOME" ] && [ "$path" != "/" ]; do
            [ -L "$path" ] && return 0
            path=$(dirname "$path")
        done
        return 1
    }

    local found=0
    while IFS= read -r -d '' source_file; do
        local rel_path=${source_file#"$package_root"/}
        local target_file="$HOME/$rel_path"
        if [ -e "$target_file" ] && [ ! -L "$target_file" ] && ! target_has_symlink_ancestor "$target_file"; then
            if [ "$found" -eq 0 ]; then
                echo "ERROR: unmanaged files are blocking stow for package '$package'."
                echo "Edit shared agent assets in the dotfiles repo source, not in installed home paths."
                echo "Conflicts:"
                found=1
            fi
            echo "  - $target_file"
            echo "    source: $source_file"
        fi
    done < <(find "$package_root" -type f -print0)

    if [ "$found" -eq 1 ]; then
        echo "Fix: move the content back into $package_root, remove the unmanaged home-path copy, then rerun ./install.sh."
        return 1
    fi
}

# Codex follows symlinked skill directories but skips a symlinked SKILL.md.
# Keep Stow's file-level layout for overlays, then materialize only manifests
# carrying this installer's ownership marker.
GENERATED_SKILL_MARKER=.wihli-dotfiles-generated
GENERATED_SKILL_OWNER="Generated by wihli-dotfiles install.sh"

is_generated_skill_marker() {
    local marker=$1
    [ -f "$marker" ] && [ ! -L "$marker" ] && \
        [ "$(cat "$marker")" = "$GENERATED_SKILL_OWNER" ]
}

remove_generated_skill_manifests() {
    local skills_dir=$1 marker skill_dir target_manifest
    [ -d "$skills_dir" ] || return 0

    for marker in "$skills_dir"/*/"$GENERATED_SKILL_MARKER"; do
        [ -e "$marker" ] || continue
        if ! is_generated_skill_marker "$marker"; then
            echo "WARNING: $marker is not owned by this installer; not removing."
            continue
        fi
        skill_dir=$(dirname "$marker")
        target_manifest="$skill_dir/SKILL.md"
        echo "Removing generated skill manifest $target_manifest for re-stow..."
        rm -f "$target_manifest" "$marker"
    done
}

materialize_skill_manifests() {
    local repo_root=$1 skills_dir=$2 source_root source_manifest skill_name
    local target_dir target_manifest marker
    source_root="$repo_root/skills/.local/share/skills"
    [ -d "$source_root" ] || return 0

    for source_manifest in "$source_root"/*/SKILL.md; do
        [ -f "$source_manifest" ] || continue
        skill_name=$(basename "$(dirname "$source_manifest")")
        target_dir="$skills_dir/$skill_name"
        target_manifest="$target_dir/SKILL.md"
        marker="$target_dir/$GENERATED_SKILL_MARKER"

        if [ ! -L "$target_manifest" ] && ! is_generated_skill_marker "$marker"; then
            echo "ERROR: cannot generate $target_manifest because it is not a Stow link owned by this installer."
            echo "Fix: move any edits into $source_manifest, remove the unmanaged installed file, then rerun ./install.sh."
            return 1
        fi

        rm -f "$target_manifest"
        cp "$source_manifest" "$target_manifest"
        printf '%s\n' "$GENERATED_SKILL_OWNER" > "$marker"
    done
}

remove_generated_skill_manifests "$HOME/.local/share/skills"

# Stow cannot transfer a target to the private overlay while a dangling
# symlink from an older public package still occupies that path. Remove only
# broken ~/.local/bin links that point back into this public repo.
for link in "$HOME/.local/bin/"*; do
    [ -L "$link" ] && [ ! -e "$link" ] || continue
    case "$(readlink "$link")" in
        *"/$(basename "$(pwd)")/"*)
            echo "Removing stale public bin symlink $link..."
            rm "$link"
            ;;
    esac
done

# Stow all packages
#   skills     -> ~/.local/share/skills/
#   subagents  -> ~/.local/share/subagents/
#   agents     -> ~/.config/AGENTS.md (the global instructions file)
#   bin        -> ~/.local/bin/ shared helper commands
#   claude     -> ~/.claude/settings.json
#   codex      -> ~/.codex/hooks.json
for pkg in bin claude codex agents skills subagents bash doom fish git starship tmux vim zellij; do
    if [ "$pkg" = "skills" ] || [ "$pkg" = "subagents" ]; then
        detect_unmanaged_stow_files "$(pwd)" "$pkg"
    fi
    echo "Stowing $pkg..."
    stow --no-folding --ignore='__pycache__' --ignore='\.pytest_cache' -t ~ "$pkg"
done

# Ensure ~/.bashrc sources ~/.bashrc.d/ (works with devcontainer-managed .bashrc)
BASHRC_HOOK='# Source drop-in configs from ~/.bashrc.d/
if [ -d "$HOME/.bashrc.d" ]; then
    for f in "$HOME/.bashrc.d"/*.bash; do
        [ -r "$f" ] && . "$f"
    done
    unset f
fi'
if [ -L ~/.bashrc ] && [ ! -e ~/.bashrc ]; then
    echo "Removing broken ~/.bashrc symlink..."
    rm ~/.bashrc
fi
if [ ! -f ~/.bashrc ]; then
    echo "Creating minimal ~/.bashrc..."
    printf '# Minimal bash initialization\n[[ $- != *i* ]] && return\n' > ~/.bashrc
fi
if ! grep -qF '# Source drop-in configs from ~/.bashrc.d/' ~/.bashrc; then
    echo "Adding .bashrc.d sourcing to ~/.bashrc..."
    printf '\n%s\n' "$BASHRC_HOOK" >> ~/.bashrc
fi

# Clone and stow private dotfiles (silently skips if no access)
SRC_DIR="${SRC_DIR:-$HOME/code}"
PRIVATE_DOTFILES="$SRC_DIR/wihli-dotfiles-private"
if [ ! -d "$PRIVATE_DOTFILES" ]; then
    echo "Cloning private dotfiles..."
    mkdir -p "$SRC_DIR"
    git clone git@github.com:wihli/dotfiles-private.git "$PRIVATE_DOTFILES" 2>/dev/null || \
        echo "Skipping private dotfiles (no SSH access)"
fi
if [ -d "$PRIVATE_DOTFILES" ]; then
    echo "Stowing private dotfiles..."
    for pkg in claude agents skills subagents fish bin oncall pi; do
        [ -d "$PRIVATE_DOTFILES/$pkg" ] || continue
        if [ "$pkg" = "skills" ] || [ "$pkg" = "subagents" ]; then
            detect_unmanaged_stow_files "$PRIVATE_DOTFILES" "$pkg"
        fi
        stow --no-folding --ignore='__pycache__' --ignore='\.pytest_cache' -t ~ -d "$PRIVATE_DOTFILES" "$pkg"
    done

    # Codex approval rules are read before tool execution and symlinked rules are
    # not picked up reliably, so install the private source as a regular file.
    PRIVATE_CODEX_RULES="$PRIVATE_DOTFILES/codex/.codex/rules/default.rules"
    if [ -f "$PRIVATE_CODEX_RULES" ]; then
        echo "Installing private Codex rules..."
        mkdir -p "$HOME/.codex/rules"
        rm -f "$HOME/.codex/rules/default.rules"
        cp "$PRIVATE_CODEX_RULES" "$HOME/.codex/rules/default.rules"
    fi

    # Merge private Codex hook groups into the public hooks file without
    # replacing unrelated public hook groups.
    PRIVATE_CODEX_HOOKS="$PRIVATE_DOTFILES/codex/.codex/hooks-private.json"
    PUBLIC_CODEX_HOOKS="$HOME/.codex/hooks.json"
    if [ -f "$PRIVATE_CODEX_HOOKS" ] && [ -f "$PUBLIC_CODEX_HOOKS" ]; then
        echo "Merging Codex hooks..."
        MERGED=$(jq -s '
          .[0] as $pub | .[1] as $priv |
          def merged_hooks:
            reduce (((($pub.hooks // {}) + ($priv.hooks // {})) | keys_unsorted)[]) as $name
              ({}; .[$name] = (($pub.hooks[$name] // []) + ($priv.hooks[$name] // [])));
          {"description": "Generated by dotfiles install.sh — do not edit directly"} *
          $pub * $priv * {hooks: merged_hooks}
        ' "$PUBLIC_CODEX_HOOKS" "$PRIVATE_CODEX_HOOKS")
        rm -f "$PUBLIC_CODEX_HOOKS"
        echo "$MERGED" > "$PUBLIC_CODEX_HOOKS"
    fi

    # Merge private settings into public settings.json
    PRIVATE_SETTINGS="$HOME/.claude/settings-private.json"
    PUBLIC_SETTINGS="$HOME/.claude/settings.json"
    if [ -f "$PRIVATE_SETTINGS" ] && [ -f "$PUBLIC_SETTINGS" ]; then
        echo "Merging Claude settings..."
        MERGED=$(jq -s '
          .[0] as $pub | .[1] as $priv |
          def merged_hooks:
            reduce (((($pub.hooks // {}) + ($priv.hooks // {})) | keys_unsorted)[]) as $name
              ({}; .[$name] = (($pub.hooks[$name] // []) + ($priv.hooks[$name] // [])));
          {"//": "Generated by dotfiles install.sh — do not edit directly"} *
          $pub * $priv * {
            permissions: ($pub.permissions * $priv.permissions * {
              allow: ($pub.permissions.allow + $priv.permissions.allow | unique)
            }),
            hooks: merged_hooks
          }
        ' "$PUBLIC_SETTINGS" "$PRIVATE_SETTINGS")
        # Replace symlink with merged real file
        rm -f "$PUBLIC_SETTINGS"
        echo "$MERGED" > "$PUBLIC_SETTINGS"
    fi

    # Concatenate private AGENTS.private.md onto the end of public AGENTS.md.
    # Every tool that reads AGENTS.md (Claude, Codex, anything future) sees
    # the private rules — no reliance on @-import support.
    PRIVATE_AGENTS="$HOME/.config/AGENTS.private.md"
    PUBLIC_AGENTS="$HOME/.config/AGENTS.md"
    if [ -f "$PRIVATE_AGENTS" ] && [ -f "$PUBLIC_AGENTS" ]; then
        echo "Merging AGENTS.md..."
        # Read both through their symlinks before we replace the public one.
        PUBLIC_CONTENT=$(cat "$PUBLIC_AGENTS")
        PRIVATE_CONTENT=$(cat "$PRIVATE_AGENTS")
        rm -f "$PUBLIC_AGENTS"
        {
            printf '<!-- Generated by dotfiles install.sh — do not edit directly.\n     Public source:  $SRC_DIR/wihli-dotfiles/agents/.config/AGENTS.md\n     Private source: $SRC_DIR/wihli-dotfiles-private/agents/.config/AGENTS.private.md -->\n\n'
            printf '%s\n\n%s\n' "$PUBLIC_CONTENT" "$PRIVATE_CONTENT"
        } > "$PUBLIC_AGENTS"
    fi
fi

materialize_skill_manifests "$(pwd)" "$HOME/.local/share/skills"
if [ -d "$PRIVATE_DOTFILES" ]; then
    materialize_skill_manifests "$PRIVATE_DOTFILES" "$HOME/.local/share/skills"
fi

# --- Multi-tool integration ------------------------------------------------
# Single source of truth lives in XDG locations; each coding-agent tool gets
# symlinks into its expected paths. Currently wired: Claude Code, Codex CLI,
# and OpenCode.

# Helper: create or refresh a symlink, only touching existing empty dirs.
ensure_link() {
    local target=$1 link=$2
    mkdir -p "$(dirname "$link")"
    if [ -L "$link" ]; then
        [ "$(readlink "$link")" = "$target" ] && return 0
        rm "$link"
    elif [ -d "$link" ]; then
        if [ -z "$(ls -A "$link")" ]; then
            rmdir "$link"
        else
            echo "WARNING: $link is a non-empty directory; not replacing. Review manually."
            return 1
        fi
    elif [ -e "$link" ]; then
        echo "WARNING: $link exists and is not a symlink; not replacing."
        return 1
    fi
    ln -s "$target" "$link"
    echo "Linked $link -> $target"
}

# Stow can leave nested empty directories behind when a shared skill is removed.
# A valid skill always has SKILL.md, so prune only empty directories bottom-up.
remove_empty_skill_dirs() {
    local skills_dir=$1
    [ -d "$skills_dir" ] || return 0

    while IFS= read -r -d '' skill_dir; do
        [ -d "$skill_dir" ] && [ ! -L "$skill_dir" ] || continue
        [ -f "$skill_dir/SKILL.md" ] && continue
        if [ -z "$(find "$skill_dir" -mindepth 1 -print -quit)" ]; then
            echo "Removing empty skill directory $skill_dir..."
            rmdir "$skill_dir"
        fi
    done < <(find "$skills_dir" -depth -mindepth 1 -type d -print0)
}

# Stow can leave dangling links at any depth inside a former skill directory.
# Remove only broken links before checking whether the directory is empty.
remove_stale_skill_entries() {
    local skills_dir=$1
    [ -d "$skills_dir" ] || return 0

    while IFS= read -r -d '' skill_entry; do
        if [ ! -e "$skill_entry" ]; then
            echo "Removing stale skill entry $skill_entry..."
            rm "$skill_entry"
        fi
    done < <(find "$skills_dir" -type l -print0)
}

# Stow leaves dangling per-skill links behind when a shared skill is removed.
# Remove only broken links from agent discovery roots; never replace real files.
remove_stale_skill_links() {
    local skills_dir=$1
    [ -d "$skills_dir" ] || return 0

    for skill_link in "$skills_dir"/*; do
        if [ -L "$skill_link" ] && [ ! -e "$skill_link" ]; then
            echo "Removing stale skill link $skill_link..."
            rm "$skill_link"
        fi
    done
}

# AGENTS.md: single source at ~/.config/AGENTS.md
if [ -f ~/.config/AGENTS.md ]; then
    # Claude Code reads ~/.claude/CLAUDE.md
    ensure_link ~/.config/AGENTS.md ~/.claude/CLAUDE.md || true
    # Codex CLI reads ~/.codex/AGENTS.md
    if [ -d ~/.codex ]; then
        ensure_link ~/.config/AGENTS.md ~/.codex/AGENTS.md || true
    fi
fi

# OpenCode agent export
# OpenCode reads agent definitions from ~/.config/opencode/agent/<name>.md. The file
# shape matches Claude's -- YAML frontmatter, then a system prompt -- but the keys do
# not: OpenCode needs `mode: subagent` before it treats a definition as a sub-agent
# rather than a primary one, and it resolves models as provider/model, so Claude's
# `sonnet` and `opus` aliases mean nothing to it. Rewriting the frontmatter is therefore
# required; a symlink would install an unusable agent. Dropping `model` lets each agent
# inherit the model in opencode.jsonc, which resolves everywhere; add a provider-
# qualified model to a generated file only after checking OpenCode accepts that id.
#
# `permissionMode` is likewise Claude-only: OpenCode spells permissions differently
# (a `permission` object), so passing it through would put an unknown key in the file.
#
# An agent that pins `tools:` is Claude-only by construction. Those lists name Claude
# tool names and mcp__* servers with no OpenCode equivalent, so exporting one produces
# an agent that cannot reach the data it exists to read. Skip it and say which.
GENERATED_AGENT_MARKER="<!-- generated by wihli-dotfiles install.sh; edit the source in wihli-dotfiles -->"

pins_claude_only_tools() {
    local file=$1
    awk '/^---$/ { fence++; next } fence == 1 && /^tools:/ { found = 1 } fence >= 2 { exit } END { exit !found }' "$file"
}

remove_generated_opencode_agents() {
    local target_dir=$1 file
    [ -d "$target_dir" ] || return 0
    for file in "$target_dir"/*.md; do
        [ -f "$file" ] || continue
        if grep -qF "$GENERATED_AGENT_MARKER" "$file"; then
            rm -f "$file"
        fi
    done
}

export_opencode_agents() {
    local source_dir=$1 target_dir=$2 file name
    [ -d "$source_dir" ] || return 0
    mkdir -p "$target_dir"
    # Clear our own previous output first so a deleted or renamed source disappears,
    # while any agent written by hand in that directory survives untouched.
    remove_generated_opencode_agents "$target_dir"
    for file in "$source_dir"/*.md; do
        [ -f "$file" ] || continue
        name=$(basename "$file" .md)
        if pins_claude_only_tools "$file"; then
            echo "Skipping OpenCode export of $name (pins Claude-only tools)"
            continue
        fi
        {
            echo "---"
            echo "mode: subagent"
            awk '/^---$/ { fence++; next } fence == 1 && !/^(name|model|tools|permissionMode):/ && !/^  - / { print } fence >= 2 { exit }' "$file"
            echo "---"
            echo "$GENERATED_AGENT_MARKER"
            awk 'fence >= 2 { print } /^---$/ { fence++ }' "$file"
        } > "$target_dir/$name.md"
    done
}

# Skills and subagents: shared XDG storage, tool dirs are directory symlinks.
remove_stale_skill_entries "$HOME/.local/share/skills"
remove_empty_skill_dirs "$HOME/.local/share/skills"
remove_stale_skill_links "$HOME/.agents/skills"
remove_stale_skill_links "$HOME/.codex/skills"
# Subagents stow per-file; a removed source leaves a dangling link behind.
remove_stale_skill_links "$HOME/.local/share/subagents"

if [ -d ~/.local/share/skills ]; then
    ensure_link ~/.local/share/skills ~/.claude/skills || true
    # Codex and OpenCode discover the shared Agent Skills user directory. Link
    # skills individually so provider-managed entries can coexist there.
    for skill_dir in ~/.local/share/skills/*/; do
        skill_name=$(basename "$skill_dir")
        [ "$skill_name" = ".system" ] && continue
        ensure_link "$skill_dir" "$HOME/.agents/skills/$skill_name" || true
    done
    if [ -d ~/.codex ]; then
        # Codex manages its own skills/ dir (with .system/ inside), so we can't
        # replace it with a directory symlink. Instead, symlink each skill individually.
        if [ -d ~/.codex/skills ] && [ ! -L ~/.codex/skills ]; then
            for skill_dir in ~/.local/share/skills/*/; do
                skill_name=$(basename "$skill_dir")
                [ "$skill_name" = ".system" ] && continue
                ensure_link "$skill_dir" "$HOME/.codex/skills/$skill_name" || true
            done
        else
            ensure_link ~/.local/share/skills ~/.codex/skills || true
        fi
    fi
fi
if [ -d ~/.local/share/subagents ]; then
    ensure_link ~/.local/share/subagents ~/.claude/agents || true
    export_opencode_agents ~/.local/share/subagents ~/.config/opencode/agent
    # Codex spawns sub-agents as runtime thread forks that inherit the current model
    # (its spawn_agent tool) and reads no agent definition files, so there is nothing
    # to install for it. Revisit when Codex grows a user-level agents directory.
fi

echo "Done! Dotfiles installed."
