#!/bin/bash
# Install dotfiles via stow
# Run from the dotfiles directory

set -e
cd "$(dirname "$0")"

# Install stow if missing
if ! command -v stow &> /dev/null; then
    echo "Installing stow..."
    if command -v apt &> /dev/null; then
        sudo apt install -y stow
    elif command -v brew &> /dev/null; then
        brew install stow
    else
        echo "Please install stow manually"
        exit 1
    fi
fi

# Clean up ~/.bashrc.d so stow can create its symlink cleanly
if [ -L ~/.bashrc.d ] && [ ! -e ~/.bashrc.d ]; then
    echo "Removing broken .bashrc.d symlink..."
    rm ~/.bashrc.d
elif [ -d ~/.bashrc.d ] && [ ! -L ~/.bashrc.d ]; then
    echo "Removing existing .bashrc.d directory..."
    rm -rf ~/.bashrc.d
fi

# Install git-delta on Linux
if [[ "$(uname)" == "Linux" ]] && ! command -v delta &> /dev/null; then
    echo "Installing git-delta..."
    DELTA_VERSION="0.18.2"
    curl -sLO "https://github.com/dandavison/delta/releases/download/${DELTA_VERSION}/git-delta_${DELTA_VERSION}_amd64.deb"
    sudo dpkg -i "git-delta_${DELTA_VERSION}_amd64.deb"
    rm "git-delta_${DELTA_VERSION}_amd64.deb"
fi

# Remove generated settings.json so stow can recreate the symlink
# (install.sh replaces it with a merged real file; stow needs a clean target)
if [ -f ~/.claude/settings.json ] && [ ! -L ~/.claude/settings.json ]; then
    echo "Removing generated settings.json for re-stow..."
    rm -f ~/.claude/settings.json
fi

# Same treatment for AGENTS.md: install.sh replaces the stow symlink with a
# real merged file (public + private concatenated). Clean it up so stow can
# recreate the symlink before merging.
if [ -f ~/.config/AGENTS.md ] && [ ! -L ~/.config/AGENTS.md ]; then
    echo "Removing generated AGENTS.md for re-stow..."
    rm -f ~/.config/AGENTS.md
fi

# Clean up legacy per-file symlinks from previous stow layouts
# (skills/agents used to stow into ~/.claude/{skills,agents}; they now live in
# ~/.local/share/{skills,subagents} and ~/.claude/{skills,agents} are dir symlinks)
for legacy in ~/.claude/skills ~/.claude/agents; do
    if [ -d "$legacy" ] && [ ! -L "$legacy" ]; then
        # Only remove if it contains nothing but symlinks (stow-managed)
        if [ -z "$(find "$legacy" -type f -print -quit 2>/dev/null)" ]; then
            echo "Removing legacy stow dir $legacy..."
            rm -rf "$legacy"
        else
            echo "WARNING: $legacy contains real files; skipping migration. Review manually."
        fi
    fi
done

# Point this repo's hooks at the versioned hooks/ directory
git -C "$(pwd)" config core.hooksPath hooks

# Stow all packages
#   skills     -> ~/.local/share/skills/
#   subagents  -> ~/.local/share/subagents/
#   agents     -> ~/.config/AGENTS.md (the global instructions file)
#   claude     -> ~/.claude/settings.json
for pkg in claude agents skills subagents bash fish git starship tmux vim zellij; do
    echo "Stowing $pkg..."
    stow --no-folding -t ~ "$pkg"
done

# Ensure ~/.bashrc sources ~/.bashrc.d/ (works with devcontainer-managed .bashrc)
BASHRC_HOOK='# Source drop-in configs from ~/.bashrc.d/
if [ -d "$HOME/.bashrc.d" ]; then
    for f in "$HOME/.bashrc.d"/*.bash; do
        [ -r "$f" ] && . "$f"
    done
    unset f
fi'
if [ -L ~/.bashrc ] && [ ! -e ~/.bashrc ]; then
    echo "Removing broken ~/.bashrc symlink..."
    rm ~/.bashrc
fi
if [ ! -f ~/.bashrc ]; then
    echo "Creating minimal ~/.bashrc..."
    printf '# Minimal bash initialization\n[[ $- != *i* ]] && return\n' > ~/.bashrc
fi
if ! grep -qF '# Source drop-in configs from ~/.bashrc.d/' ~/.bashrc; then
    echo "Adding .bashrc.d sourcing to ~/.bashrc..."
    printf '\n%s\n' "$BASHRC_HOOK" >> ~/.bashrc
fi

# Clone and stow private dotfiles (silently skips if no access)
PRIVATE_DOTFILES="$HOME/src/wihli-dotfiles-private"
if [ ! -d "$PRIVATE_DOTFILES" ]; then
    echo "Cloning private dotfiles..."
    mkdir -p "$HOME/src"
    git clone git@github.com:wihli/dotfiles-private.git "$PRIVATE_DOTFILES" 2>/dev/null || \
        echo "Skipping private dotfiles (no SSH access)"
fi
if [ -d "$PRIVATE_DOTFILES" ]; then
    echo "Stowing private dotfiles..."
    for pkg in claude agents skills subagents fish bin oncall; do
        [ -d "$PRIVATE_DOTFILES/$pkg" ] || continue
        stow --no-folding -t ~ -d "$PRIVATE_DOTFILES" "$pkg"
    done

    # Merge private settings into public settings.json
    PRIVATE_SETTINGS="$HOME/.claude/settings-private.json"
    PUBLIC_SETTINGS="$HOME/.claude/settings.json"
    if [ -f "$PRIVATE_SETTINGS" ] && [ -f "$PUBLIC_SETTINGS" ]; then
        echo "Merging Claude settings..."
        MERGED=$(jq -s '
          .[0] as $pub | .[1] as $priv |
          {"//": "Generated by dotfiles install.sh — do not edit directly"} *
          $pub * {permissions: ($pub.permissions * {
            allow: ($pub.permissions.allow + $priv.permissions.allow | unique)
          })}
        ' "$PUBLIC_SETTINGS" "$PRIVATE_SETTINGS")
        # Replace symlink with merged real file
        rm -f "$PUBLIC_SETTINGS"
        echo "$MERGED" > "$PUBLIC_SETTINGS"
    fi

    # Concatenate private AGENTS.private.md onto the end of public AGENTS.md.
    # Every tool that reads AGENTS.md (Claude, Codex, anything future) sees
    # the private rules — no reliance on @-import support.
    PRIVATE_AGENTS="$HOME/.config/AGENTS.private.md"
    PUBLIC_AGENTS="$HOME/.config/AGENTS.md"
    if [ -f "$PRIVATE_AGENTS" ] && [ -f "$PUBLIC_AGENTS" ]; then
        echo "Merging AGENTS.md..."
        # Read both through their symlinks before we replace the public one.
        PUBLIC_CONTENT=$(cat "$PUBLIC_AGENTS")
        PRIVATE_CONTENT=$(cat "$PRIVATE_AGENTS")
        rm -f "$PUBLIC_AGENTS"
        {
            printf '<!-- Generated by dotfiles install.sh — do not edit directly.\n     Public source:  ~/src/wihli-dotfiles/agents/.config/AGENTS.md\n     Private source: ~/src/wihli-dotfiles-private/agents/.config/AGENTS.private.md -->\n\n'
            printf '%s\n\n%s\n' "$PUBLIC_CONTENT" "$PRIVATE_CONTENT"
        } > "$PUBLIC_AGENTS"
    fi
fi

# --- Multi-tool integration ------------------------------------------------
# Single source of truth lives in XDG locations; each coding-agent tool gets
# symlinks into its expected paths. Currently wired: Claude Code, Codex CLI.

# Helper: create or refresh a symlink, only touching existing empty dirs.
ensure_link() {
    local target=$1 link=$2
    mkdir -p "$(dirname "$link")"
    if [ -L "$link" ]; then
        [ "$(readlink "$link")" = "$target" ] && return 0
        rm "$link"
    elif [ -d "$link" ]; then
        if [ -z "$(ls -A "$link")" ]; then
            rmdir "$link"
        else
            echo "WARNING: $link is a non-empty directory; not replacing. Review manually."
            return 1
        fi
    elif [ -e "$link" ]; then
        echo "WARNING: $link exists and is not a symlink; not replacing."
        return 1
    fi
    ln -s "$target" "$link"
    echo "Linked $link -> $target"
}

# AGENTS.md: single source at ~/.config/AGENTS.md
if [ -f ~/.config/AGENTS.md ]; then
    # Claude Code reads ~/.claude/CLAUDE.md
    ensure_link ~/.config/AGENTS.md ~/.claude/CLAUDE.md || true
    # Codex CLI reads ~/.codex/AGENTS.md
    if [ -d ~/.codex ]; then
        ensure_link ~/.config/AGENTS.md ~/.codex/AGENTS.md || true
    fi
fi

# Skills and subagents: shared XDG storage, tool dirs are directory symlinks.
if [ -d ~/.local/share/skills ]; then
    ensure_link ~/.local/share/skills ~/.claude/skills || true
    if [ -d ~/.codex ]; then
        # Codex manages its own skills/ dir (with .system/ inside), so we can't
        # replace it with a directory symlink. Instead, symlink each skill individually.
        if [ -d ~/.codex/skills ] && [ ! -L ~/.codex/skills ]; then
            for skill_dir in ~/.local/share/skills/*/; do
                skill_name=$(basename "$skill_dir")
                [ "$skill_name" = ".system" ] && continue
                ensure_link "$skill_dir" "$HOME/.codex/skills/$skill_name" || true
            done
        else
            ensure_link ~/.local/share/skills ~/.codex/skills || true
        fi
    fi
fi
if [ -d ~/.local/share/subagents ]; then
    ensure_link ~/.local/share/subagents ~/.claude/agents || true
    # Codex has no native subagent concept yet; skip.
fi

echo "Done! Symlinks created."
