from pathlib import Path
import subprocess
import tempfile
import unittest


REPO_ROOT = Path(__file__).resolve().parents[1]


class InstallScriptTests(unittest.TestCase):
    def test_private_pi_extensions_are_stowed(self) -> None:
        install_script = (REPO_ROOT / "install.sh").read_text()

        self.assertRegex(install_script, r"for pkg in [^\n]*\bpi\b[^\n]*; do")

    def test_install_script_has_valid_bash_syntax(self) -> None:
        result = subprocess.run(
            ["bash", "-n", str(REPO_ROOT / "install.sh")],
            capture_output=True,
            text=True,
        )

        self.assertEqual(0, result.returncode, result.stderr)

    def test_codex_hooks_merge_uses_supported_top_level_metadata(self) -> None:
        install_script = (REPO_ROOT / "install.sh").read_text()
        codex_merge = install_script.split(
            "# Merge private Codex hook groups", maxsplit=1
        )[1].split("# Merge private settings", maxsplit=1)[0]

        self.assertIn(
            '{"description": "Generated by dotfiles install.sh — do not edit directly"}',
            codex_merge,
        )
        self.assertNotIn('{"//":', codex_merge)

    def test_skill_cleanup_removes_dangling_links_and_empty_nested_dirs(self) -> None:
        install_script = (REPO_ROOT / "install.sh").read_text()

        self.assertIn("remove_empty_skill_dirs() {", install_script)
        self.assertIn(
            'remove_empty_skill_dirs "$HOME/.local/share/skills"', install_script
        )
        self.assertIn("remove_stale_skill_entries() {", install_script)
        self.assertIn(
            'remove_stale_skill_entries "$HOME/.local/share/skills"',
            install_script,
        )
        self.assertIn(
            'find "$skills_dir" -depth -mindepth 1 -type d -print0',
            install_script,
        )
        self.assertIn('find "$skills_dir" -type l -print0', install_script)
        self.assertIn("remove_stale_skill_links() {", install_script)
        self.assertIn(
            'if [ -L "$skill_link" ] && [ ! -e "$skill_link" ]; then',
            install_script,
        )
        self.assertIn(
            'remove_stale_skill_links "$HOME/.agents/skills"', install_script
        )
        self.assertIn(
            'remove_stale_skill_links "$HOME/.codex/skills"', install_script
        )

    def test_dotfiles_skill_manifests_are_materialized_without_changing_layout(self) -> None:
        install_script = (REPO_ROOT / "install.sh").read_text()

        self.assertIn("remove_generated_skill_manifests() {", install_script)
        self.assertIn("materialize_skill_manifests() {", install_script)
        self.assertIn(
            'remove_generated_skill_manifests "$HOME/.local/share/skills"',
            install_script,
        )
        self.assertIn(
            'materialize_skill_manifests "$(pwd)" "$HOME/.local/share/skills"',
            install_script,
        )
        self.assertIn(
            'materialize_skill_manifests "$PRIVATE_DOTFILES" "$HOME/.local/share/skills"',
            install_script,
        )
        self.assertIn('rm -f "$target_manifest"', install_script)
        self.assertIn('cp "$source_manifest" "$target_manifest"', install_script)
        self.assertIn("$GENERATED_SKILL_OWNER", install_script)
        self.assertIn("stow --no-folding", install_script)

        cleanup = install_script.index(
            'remove_generated_skill_manifests "$HOME/.local/share/skills"'
        )
        public_stow = install_script.index("# Stow all packages")
        materialize = install_script.index(
            'materialize_skill_manifests "$(pwd)" "$HOME/.local/share/skills"'
        )
        integrations = install_script.index("# --- Multi-tool integration")
        self.assertLess(cleanup, public_stow)
        self.assertGreater(materialize, public_stow)
        self.assertLess(materialize, integrations)

    def test_generated_skill_manifest_lifecycle_preserves_unowned_skills(self) -> None:
        install_script = (REPO_ROOT / "install.sh").read_text()
        functions = install_script.split(
            "# Codex follows symlinked skill directories", maxsplit=1
        )[1].split(
            'remove_generated_skill_manifests "$HOME/.local/share/skills"',
            maxsplit=1,
        )[0]

        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            repo = root / "dotfiles"
            source_manifest = repo / "skills/.local/share/skills/example/SKILL.md"
            source_manifest.parent.mkdir(parents=True)
            source_manifest.write_text("---\nname: example\ndescription: Test skill.\n---\n")

            skills_dir = root / "home/.local/share/skills"
            target_manifest = skills_dir / "example/SKILL.md"
            target_manifest.parent.mkdir(parents=True)
            target_manifest.symlink_to(source_manifest)

            unowned_manifest = skills_dir / "third-party/SKILL.md"
            unowned_manifest.parent.mkdir(parents=True)
            unowned_manifest.write_text("third-party\n")
            unowned_marker = unowned_manifest.parent / ".wihli-dotfiles-generated"
            unowned_marker.write_text("not owned by this installer\n")

            function_file = root / "skill-functions.sh"
            function_file.write_text(functions)
            materialized = subprocess.run(
                [
                    "bash",
                    "-c",
                    'source "$1"; materialize_skill_manifests "$2" "$3"',
                    "bash",
                    str(function_file),
                    str(repo),
                    str(skills_dir),
                ],
                capture_output=True,
                text=True,
            )
            self.assertEqual(0, materialized.returncode, materialized.stderr)
            self.assertFalse(target_manifest.is_symlink())
            self.assertEqual(source_manifest.read_text(), target_manifest.read_text())

            source_manifest.unlink()
            cleaned = subprocess.run(
                [
                    "bash",
                    "-c",
                    'source "$1"; remove_generated_skill_manifests "$2"',
                    "bash",
                    str(function_file),
                    str(skills_dir),
                ],
                capture_output=True,
                text=True,
            )
            self.assertEqual(0, cleaned.returncode, cleaned.stderr)
            self.assertFalse(target_manifest.exists())
            self.assertEqual("third-party\n", unowned_manifest.read_text())
            self.assertTrue(unowned_marker.exists())


    def test_opencode_export_adapts_frontmatter_and_skips_claude_only_agents(self) -> None:
        install_script = (REPO_ROOT / "install.sh").read_text()
        functions = install_script.split("# OpenCode agent export", maxsplit=1)[1].split(
            "# Skills and subagents: shared XDG storage", maxsplit=1
        )[0]

        with tempfile.TemporaryDirectory() as tmp:
            root = Path(tmp)
            source = root / "subagents"
            source.mkdir()
            (source / "portable.md").write_text(
                "---\nname: portable\ndescription: |\n  Does a thing.\nmodel: opus\npermissionMode: auto\n---\n\nBody line.\n"
            )
            (source / "claude-only.md").write_text(
                "---\nname: claude-only\ndescription: Reads Datadog.\ntools:\n"
                "  - Bash\n  - mcp__datadog__search-logs\n---\n\nBody.\n"
            )
            target = root / "agent"
            target.mkdir()
            handwritten = target / "mine.md"
            handwritten.write_text("---\nmode: subagent\n---\n\nHand written.\n")

            function_file = root / "opencode-functions.sh"
            function_file.write_text(functions)
            run = lambda: subprocess.run(
                [
                    "bash",
                    "-c",
                    'source "$1"; export_opencode_agents "$2" "$3"',
                    "bash",
                    str(function_file),
                    str(source),
                    str(target),
                ],
                capture_output=True,
                text=True,
            )
            result = run()
            self.assertEqual(0, result.returncode, result.stderr)
            self.assertIn("Skipping OpenCode export of claude-only", result.stdout)

            exported = (target / "portable.md").read_text()
            self.assertIn("mode: subagent", exported)
            self.assertIn("Does a thing.", exported)
            self.assertIn("Body line.", exported)
            # Claude's model aliases and tool names do not resolve in OpenCode.
            self.assertNotIn("model: opus", exported)
            self.assertNotIn("permissionMode", exported)
            self.assertNotIn("name: portable", exported)
            self.assertFalse((target / "claude-only.md").exists())

            # Re-running is idempotent, drops a deleted source, and leaves hand-written
            # agents in place.
            (source / "portable.md").unlink()
            self.assertEqual(0, run().returncode)
            self.assertFalse((target / "portable.md").exists())
            self.assertEqual("---\nmode: subagent\n---\n\nHand written.\n", handwritten.read_text())


if __name__ == "__main__":
    unittest.main()
