from pathlib import Path
import unittest


REPO_ROOT = Path(__file__).resolve().parents[1]


class InstallScriptTests(unittest.TestCase):
    def test_codex_hooks_merge_uses_supported_top_level_metadata(self) -> None:
        install_script = (REPO_ROOT / "install.sh").read_text()
        codex_merge = install_script.split(
            "# Merge private Codex hook groups", maxsplit=1
        )[1].split("# Merge private settings", maxsplit=1)[0]

        self.assertIn(
            '{"description": "Generated by dotfiles install.sh — do not edit directly"}',
            codex_merge,
        )
        self.assertNotIn('{"//":', codex_merge)


if __name__ == "__main__":
    unittest.main()
