from pathlib import Path
import unittest


REPO_ROOT = Path(__file__).resolve().parents[1]


class InstallScriptTests(unittest.TestCase):
    def test_codex_hooks_merge_uses_supported_top_level_metadata(self) -> None:
        install_script = (REPO_ROOT / "install.sh").read_text()
        codex_merge = install_script.split(
            "# Merge private Codex hook groups", maxsplit=1
        )[1].split("# Merge private settings", maxsplit=1)[0]

        self.assertIn(
            '{"description": "Generated by dotfiles install.sh — do not edit directly"}',
            codex_merge,
        )
        self.assertNotIn('{"//":', codex_merge)

    def test_skill_cleanup_removes_dangling_links_and_empty_nested_dirs(self) -> None:
        install_script = (REPO_ROOT / "install.sh").read_text()

        self.assertIn("remove_empty_skill_dirs() {", install_script)
        self.assertIn(
            'remove_empty_skill_dirs "$HOME/.local/share/skills"', install_script
        )
        self.assertIn("remove_stale_skill_entries() {", install_script)
        self.assertIn(
            'remove_stale_skill_entries "$HOME/.local/share/skills"',
            install_script,
        )
        self.assertIn(
            'find "$skills_dir" -depth -mindepth 1 -type d -print0',
            install_script,
        )
        self.assertIn('find "$skills_dir" -type l -print0', install_script)
        self.assertIn("remove_stale_skill_links() {", install_script)
        self.assertIn(
            'if [ -L "$skill_link" ] && [ ! -e "$skill_link" ]; then',
            install_script,
        )
        self.assertIn(
            'remove_stale_skill_links "$HOME/.agents/skills"', install_script
        )
        self.assertIn(
            'remove_stale_skill_links "$HOME/.codex/skills"', install_script
        )


if __name__ == "__main__":
    unittest.main()
